export const NASPI_CONSTANTS = {
    THRESHOLD_AMOUNT: 1425.21,
    MAX_MONTHLY_CAP: 1550.42,
    COEFF_WEEKS_TO_MONTHS: 4.33,
    PERCENTAGE_BASE: 0.75,
    PERCENTAGE_EXCESS: 0.25,
    REDUCTION_START_MONTH: 6,
    REDUCTION_START_MONTH_OVER_55: 8,
    REDUCTION_PERCENTAGE: 0.03,
    SEPARATE_TAXATION_RATE_ESTIMATE: 0.23,
};
